title: CoFloCo
description: CoFloCo is a static analysis tool written in prolog to infer automatically symbolic complexity bounds of imperative and recursive programs.
google_analytics: UA-69257705-1
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
