//Generated by c2fsm  -cut -int
model relation1 {
var x,y;
//@parameters;
states stop,start,lbl_5_18;
transition t_41 :={
  from  := start;
  to    := lbl_5_18;
  guard := true;
  action:= x' = ?;
};
transition t_37 :={
  from  := lbl_5_18;
  to    := stop;
  guard := true;
  action:= y' = x;
};
}
strategy dumb {
    Region init := { state = start && true };
}
