(* * * * * * * * * * *
 * Resource Aware ML *
 * * * * * * * * * * *
 *
 * * *  Use Cases  * *
 *
 * File:
 *   examples/eratosthenes.raml
 *
 * Author:
 *   Ankush Das, Jan Hoffmann (2015)
 * 
 * Description:
 *   Sieve of Eratosthenes.
 *)


let rec filter p l =
	match l with
	| [] -> []
	| x::xs ->
		(Raml.tick(1.0); 
		let xs' = filter p xs in
		if (x mod p = 0) then xs'
		else x::xs');;

let rec eratos l =
	match l with
	| [] -> []
	| x::xs -> (Raml.tick(1.0); x::(eratos (filter x xs)));;

eratos [2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20]
