(* * * * * * * * * * *
 * Resource Aware ML *
 * * * * * * * * * * *
 *
 * * *  Use Cases  * *
 *
 * File:
 *   examples/minsort.raml
 *
 * Author:
 *   Ankush Das, Jan Hoffmann (2015)
 * 
 * Description:
 *   An implementation of the sorting algorithm selection sort.
 *   (See http://en.wikipedia.org/wiki/Selection_sort)
 *)



let rec findMin l =
	match l with
	| [] -> []
	| x::xs ->
		match (findMin xs) with
		| [] -> [x]
		| y::ys ->
			(Raml.tick(1.0); 
			if ((x:int) < (y:int)) then x::y::ys
			else y::x::ys);;

let rec minSort l =
	match (findMin l) with
	| [] -> []
	| x::xs -> (Raml.tick(1.0); x::minSort xs);;


minSort [9;4;5;6;1;2;3;0;0]
