(* * * * * * * * * * *
 * Resource Aware ML *
 * * * * * * * * * * *
 *
 * * *  Use Cases  * *
 *
 * File:
 *   tests/dyade.raml
 *
 * Author:
 *   Ankush Das, Jan Hoffmann (2015)
 * 
 * Description:
 *   Compute the dyadic product of two vectors.
 *)


let rec mult n l =
	match l with
	| [] -> []
	| x::xs -> (Raml.tick(1.0); n*x::(mult n xs));;

let rec dyade l1 l2 =
	match l1 with
	| [] -> []
	| x::xs -> (Raml.tick(1.0); (mult x l2)::(dyade xs l2));;

dyade [1;2;3;4;5] [1;2;3]
