(* * * * * * * * * * *
 * Resource Aware ML *
 * * * * * * * * * * *
 *
 * * *  Unit Tests * *
 *
 * File:
 *   tests/raml1_appedn_all.raml
 *
 * Author:
 *   Jan Hoffmann, Shu-Chun Weng (2015)
 * 
 * Description:
 *   Append all from old raml implementation.
 *   
 *)


let rec append l1 l2  =
  match l1 with
    | [] -> l2
    | x::xs -> x::(append xs l2)


let rec append_all l =
  match l with
    | [] -> []
    | l1::ls -> append l1 (append_all ls)


let rec append_all2 l =
  match l with
    | [] -> []
    | l1::ls -> append (append_all l1) (append_all2 ls)


let rec append_all3 l =
  match l with
    | [] -> []
    | l1::ls -> append (append_all2 l1) (append_all3 ls)




