(* * * * * * * * * * *
 * Resource Aware ML *
 * * * * * * * * * * *
 *
 * * *  Use Cases  * *
 *
 * File:
 *   tests/listsort.raml
 *
 * Author:
 *   Ankush Das, Jan Hoffmann (2015)
 * 
 * Description:
 *   Insertion sort for lists of lists.
 *)


let rec leq l1 l2 =
	match l1 with
	| [] -> true
	| x::xs ->
		match l2 with
		| [] -> false
		| y::ys ->
			(Raml.tick(1.0); ((x:int) <= (y:int)) && leq xs ys);;

let rec insert x l =
	match l with
	| [] -> [x]
	| y::ys ->
		(Raml.tick(1.0);
		if (leq x y) then x::y::ys
		else y::insert x ys);;

let rec isortlist l =
	match l with
	| [] -> []
	| x::xs -> (Raml.tick(1.0); insert x (isortlist xs));;


isortlist [[1;2;3;4] ;  [1;2;3;4;5] ; [1;2;3;4;6] ; [1;2;3]]
